'use client';

import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';

type User={id:number;full_name:string;email:string;role:'admin'|'authorizer'|'hrm'|'worker';active:boolean;worker_id:number|null};
type Worker={id:number;full_name:string};

export default function UsersPage(){
  const router=useRouter();
  const [users,setUsers]=useState<User[]>([]);const [workers,setWorkers]=useState<Worker[]>([]);const [error,setError]=useState('');const [saving,setSaving]=useState(false);
  const [form,setForm]=useState({full_name:'',email:'',password:'',role:'worker',worker_id:''});
  async function load(){setError('');const [u,d]=await Promise.all([fetch('/api/users',{cache:'no-store'}),fetch('/api/dashboard',{cache:'no-store'})]);if(u.status===401){router.replace('/login');return}if(u.status===403){router.replace('/');return}const ub=await u.json(),db=await d.json();if(!u.ok)throw new Error(ub.error||'Could not load users.');setUsers(ub.users||[]);setWorkers(db.workers||[])}
  useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:'Could not load users.'))},[]);
  async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{const r=await fetch('/api/users',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,worker_id:form.worker_id||null})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Could not create user.');setForm({full_name:'',email:'',password:'',role:'worker',worker_id:''});await load()}catch(e){setError(e instanceof Error?e.message:'Could not create user.')}finally{setSaving(false)}}
  return <main style={{minHeight:'100vh',background:'var(--bg)',color:'var(--text)',padding:24}}><div style={{maxWidth:1000,margin:'0 auto'}}><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',marginBottom:24}}><div><p className="eyebrow">WORKLY ADMIN</p><h1 style={{margin:0}}>User management</h1><p className="subtle">Create accounts and assign Admin, Authorizer, HRM, or Worker roles.</p></div><button className="secondary" onClick={()=>router.push('/')}>← Back</button></div>{error&&<div className="error-banner">{error}</div>}<div style={{display:'grid',gridTemplateColumns:'minmax(280px,380px) 1fr',gap:20,alignItems:'start',marginTop:24}}><form onSubmit={submit} style={{display:'grid',gap:14,padding:20,border:'1px solid var(--border)',borderRadius:16,background:'var(--surface)',boxShadow:'var(--shadow)'}}><h2 style={{margin:0}}>Add user</h2><label style={{display:'grid',gap:6,fontWeight:700}}>Full name<input required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label style={{display:'grid',gap:6,fontWeight:700}}>Email<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label style={{display:'grid',gap:6,fontWeight:700}}>Temporary password<input type="password" minLength={8} required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label style={{display:'grid',gap:6,fontWeight:700}}>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="admin">Admin</option><option value="authorizer">Authorizer</option><option value="hrm">HRM</option><option value="worker">Worker</option></select></label><label style={{display:'grid',gap:6,fontWeight:700}}>Linked worker (optional)<select value={form.worker_id} onChange={e=>setForm({...form,worker_id:e.target.value})}><option value="">Not linked</option>{workers.map(w=><option key={w.id} value={w.id}>{w.full_name}</option>)}</select></label><button className="primary" disabled={saving}>{saving?'Creating…':'Create user'}</button></form><section style={{border:'1px solid var(--border)',borderRadius:16,background:'var(--surface)',boxShadow:'var(--shadow)',overflow:'hidden'}}>{users.map(u=><div key={u.id} style={{display:'grid',gridTemplateColumns:'1fr auto',gap:14,padding:'16px 18px',borderBottom:'1px solid var(--border)',alignItems:'center'}}><div><strong>{u.full_name}</strong><div style={{fontSize:13,color:'var(--muted)',marginTop:4}}>{u.email}</div></div><span style={{padding:'6px 10px',borderRadius:999,background:'var(--accent-soft)',color:'var(--accent)',fontSize:12,fontWeight:800,textTransform:'uppercase'}}>{u.role}</span></div>)}</section></div></div></main>
}
