'use client';

import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';

export default function SetupPage(){
  const router=useRouter();
  const [form,setForm]=useState({full_name:'',email:'',password:''});const [error,setError]=useState('');const [saving,setSaving]=useState(false);const [checking,setChecking]=useState(true);
  useEffect(()=>{fetch('/api/auth/status',{cache:'no-store'}).then(r=>r.json()).then(b=>{if(b.user)router.replace('/');else if(!b.setupRequired)router.replace('/login')}).finally(()=>setChecking(false))},[router]);
  async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{const r=await fetch('/api/auth/setup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const b=await r.json();if(!r.ok)throw new Error(b.error||'Could not create admin account.');router.replace('/');router.refresh()}catch(e){setError(e instanceof Error?e.message:'Could not create admin account.')}finally{setSaving(false)}}
  if(checking)return <main className="loading">Loading…</main>;
  return <main style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:20,background:'var(--bg)',color:'var(--text)'}}><form onSubmit={submit} style={{width:'min(460px,100%)',display:'grid',gap:16,padding:28,border:'1px solid var(--border)',borderRadius:20,background:'var(--surface)',boxShadow:'var(--shadow)'}}><div><div style={{width:46,height:46,borderRadius:14,display:'grid',placeItems:'center',background:'var(--accent)',color:'#fff',fontWeight:900,marginBottom:18}}>W</div><h1 style={{margin:0}}>Create first Admin</h1><p style={{color:'var(--muted)'}}>This one-time setup creates the first Workly administrator. The setup page closes after this account exists.</p></div>{error&&<div className="error-banner" style={{marginTop:0}}>{error}</div>}<label style={{display:'grid',gap:7,fontWeight:700}}>Full name<input required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} style={{padding:12,borderRadius:10,border:'1px solid var(--border-strong)',background:'var(--input-bg)',color:'var(--text)'}}/></label><label style={{display:'grid',gap:7,fontWeight:700}}>Email<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})} style={{padding:12,borderRadius:10,border:'1px solid var(--border-strong)',background:'var(--input-bg)',color:'var(--text)'}}/></label><label style={{display:'grid',gap:7,fontWeight:700}}>Password<input type="password" minLength={8} required value={form.password} onChange={e=>setForm({...form,password:e.target.value})} style={{padding:12,borderRadius:10,border:'1px solid var(--border-strong)',background:'var(--input-bg)',color:'var(--text)'}}/></label><button className="primary" disabled={saving}>{saving?'Creating…':'Create Admin account'}</button></form></main>
}
