'use client';

import {useEffect,useMemo,useState} from 'react';
type Worker={id:number;full_name:string;role_title:string|null;email:string|null;weekly_target_hours:number};
type Shift={id:number;worker_id:number;title:string;starts_at:string;ends_at:string;status:string;notes:string|null};
type Leave={id:number;worker_id:number;worker_name:string;leave_type:string;starts_on:string;ends_on:string;reason:string|null;status:'pending'|'approved'|'rejected'|'cancelled'};
type Av={id:number;worker_id:number;worker_name:string;weekday:number;start_time:string;end_time:string;is_available:boolean;note:string|null};
type Data={workers:Worker[];shifts:Shift[];leaveRequests:Leave[];availability:Av[]};
type Panel='schedule'|'workers'|'availability'|'leave';
const dayNames=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
const dk=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const monday=(x:Date)=>{const d=new Date(x),n=d.getDay();d.setDate(d.getDate()+(n===0?-6:1-n));d.setHours(0,0,0,0);return d};
const ft=(v:string)=>new Date(v).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
const fd=(v:string)=>new Date(v.slice(0,10)+'T00:00:00').toLocaleDateString();

export default function Home(){
 const [data,setData]=useState<Data>({workers:[],shifts:[],leaveRequests:[],availability:[]});
 const [panel,setPanel]=useState<Panel>('schedule');const [week,setWeek]=useState(()=>monday(new Date()));
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const [workerModal,setWorkerModal]=useState(false),[shiftModal,setShiftModal]=useState(false),[leaveModal,setLeaveModal]=useState(false),[avModal,setAvModal]=useState(false);
 const [workerForm,setWorkerForm]=useState({full_name:'',role_title:'',email:'',weekly_target_hours:'40'});
 const [shiftForm,setShiftForm]=useState({worker_id:'',title:'Shift',date:dk(new Date()),start:'09:00',end:'17:00',notes:''});
 const [leaveForm,setLeaveForm]=useState({worker_id:'',leave_type:'annual',starts_on:dk(new Date()),ends_on:dk(new Date()),reason:''});
 const [avForm,setAvForm]=useState({worker_id:'',weekday:'1',start_time:'09:00',end_time:'17:00',is_available:true,note:''});
 async function load(){setLoading(true);try{const r=await fetch('/api/dashboard',{cache:'no-store'});const b=await r.json();if(!r.ok)throw new Error(b.error||'Load failed');setData({workers:b.workers||[],shifts:b.shifts||[],leaveRequests:b.leaveRequests||[],availability:b.availability||[]})}catch(e){setError(e instanceof Error?e.message:'Load failed')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const days=useMemo(()=>Array.from({length:7},(_,i)=>{const d=new Date(week);d.setDate(d.getDate()+i);return d}),[week]);
 const weekly=data.shifts.filter(s=>{const d=new Date(s.starts_at);return d>=week&&d<new Date(week.getTime()+604800000)});
 const pending=data.leaveRequests.filter(x=>x.status==='pending').length;
 const initials=(n:string)=>n.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();
 async function post(url:string,payload:any,done:()=>void){setSaving(true);setError('');try{const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok)throw new Error(b.error||'Request failed');done();await load()}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{setSaving(false)}}
 async function del(url:string){const r=await fetch(url,{method:'DELETE'});const b=await r.json();if(!r.ok){setError(b.error||'Delete failed');return}await load()}
 async function review(id:number,status:'approved'|'rejected'){setSaving(true);try{const r=await fetch('/api/leave',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,status})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Update failed');await load()}catch(e){setError(e instanceof Error?e.message:'Update failed')}finally{setSaving(false)}}
 const openShift=()=>{const w=data.workers[0];setShiftForm({worker_id:w?String(w.id):'',title:'Shift',date:dk(days[0]||new Date()),start:'09:00',end:'17:00',notes:''});setShiftModal(true)};
 const openLeave=()=>{const w=data.workers[0],d=dk(new Date());setLeaveForm({worker_id:w?String(w.id):'',leave_type:'annual',starts_on:d,ends_on:d,reason:''});setLeaveModal(true)};
 const openAv=()=>{const w=data.workers[0];setAvForm({worker_id:w?String(w.id):'',weekday:'1',start_time:'09:00',end_time:'17:00',is_available:true,note:''});setAvModal(true)};
 const titles:Record<Panel,string>={schedule:'Schedule',workers:'Workers',availability:'Availability',leave:'Leave requests'};
 return <main className="app-shell">
  <aside className="sidebar"><div className="brand"><div className="brand-mark">W</div><div><strong>Workly</strong><span>Scheduler</span></div></div><nav>
   {(['schedule','workers','availability','leave'] as Panel[]).map(p=><button key={p} className={panel===p?'active':''} onClick={()=>setPanel(p)}>{p==='leave'?`Leave requests${pending?` (${pending})`:''}`:titles[p]}</button>)}<button disabled>Reports</button>
  </nav><div className="profile"><div className="avatar">AD</div><div><strong>Admin</strong><span>Administrator</span></div></div></aside>
  <section className="content"><header className="topbar"><div><p className="eyebrow">WORKFORCE MANAGEMENT</p><h1>{titles[panel]}</h1><p className="subtle">{panel==='availability'?'Define recurring weekly availability and unavailable periods.':panel==='leave'?'Review and manage time off.':panel==='workers'?'Manage workers.':'Plan shifts and prevent conflicts.'}</p></div><div className="top-actions">
   {panel==='schedule'&&<><button className="secondary" onClick={()=>setWorkerModal(true)}>+ Worker</button><button className="primary" onClick={openShift} disabled={!data.workers.length}>+ Add shift</button></>}
   {panel==='workers'&&<button className="primary" onClick={()=>setWorkerModal(true)}>+ Worker</button>}
   {panel==='availability'&&<button className="primary" onClick={openAv} disabled={!data.workers.length}>+ Availability</button>}
   {panel==='leave'&&<button className="primary" onClick={openLeave} disabled={!data.workers.length}>+ Request leave</button>}
  </div></header>{error&&<div className="error-banner">{error}</div>}{loading?<div className="loading">Loading…</div>:panel==='schedule'?<>
   <section className="stats"><article><span>Scheduled hours</span><strong>{weekly.reduce((n,s)=>n+(new Date(s.ends_at).getTime()-new Date(s.starts_at).getTime())/3600000,0).toFixed(1)}h</strong><small>This week</small></article><article><span>Workers</span><strong>{data.workers.length}</strong><small>Active</small></article><article><span>Shifts</span><strong>{weekly.length}</strong><small>This week</small></article><article><span>Pending leave</span><strong>{pending}</strong><small>Needs review</small></article></section>
   <section className="calendar-card"><div className="calendar-toolbar"><div className="toolbar-left"><button onClick={()=>{const d=new Date(week);d.setDate(d.getDate()-7);setWeek(d)}}>‹</button><button onClick={()=>setWeek(monday(new Date()))}>Today</button><button onClick={()=>{const d=new Date(week);d.setDate(d.getDate()+7);setWeek(d)}}>›</button><strong>{days[0].toLocaleDateString()} – {days[6].toLocaleDateString()}</strong></div></div><div className="schedule-grid"><div className="corner">Worker</div>{days.map(d=><div className="day-head" key={dk(d)}>{d.toLocaleDateString(undefined,{weekday:'short',day:'numeric'})}</div>)}{data.workers.map(w=><div className="row-fragment" key={w.id}><div className="worker-cell"><div className="avatar small">{initials(w.full_name)}</div><div><strong>{w.full_name}</strong><span>{w.role_title||'Worker'}</span></div></div>{days.map(d=>{const key=dk(d);const onLeave=data.leaveRequests.some(r=>r.worker_id===w.id&&r.status==='approved'&&r.starts_on.slice(0,10)<=key&&r.ends_on.slice(0,10)>=key);const shifts=weekly.filter(s=>s.worker_id===w.id&&dk(new Date(s.starts_at))===key);return <div className={`shift-cell ${onLeave?'leave-day':''}`} key={key}>{onLeave&&<div className="leave-chip">On leave</div>}{shifts.map(s=><button className="shift" key={s.id} onClick={()=>confirm('Delete this shift?')&&del(`/api/shifts?id=${s.id}`)}><strong>{s.title}</strong><span>{ft(s.starts_at)} – {ft(s.ends_at)}</span></button>)}</div>})}</div>)}</div></section>
  </>:panel==='workers'?<section className="workers-card"><div className="workers-table"><div className="table-head"><span>Name</span><span>Role</span><span>Email</span><span>Target</span></div>{data.workers.map(w=><div className="table-row" key={w.id}><span><div className="avatar small">{initials(w.full_name)}</div><strong>{w.full_name}</strong></span><span>{w.role_title||'—'}</span><span>{w.email||'—'}</span><span>{w.weekly_target_hours}h/week</span></div>)}</div></section>:panel==='availability'?<section className="workers-card"><div className="availability-list">{data.workers.map(w=><article className="availability-worker" key={w.id}><div className="availability-worker-head"><strong>{w.full_name}</strong><span>{w.role_title||'Worker'}</span></div><div className="availability-rules">{data.availability.filter(a=>a.worker_id===w.id).length===0?<span className="muted">No rules — schedulable any time.</span>:data.availability.filter(a=>a.worker_id===w.id).map(a=><div className={`availability-rule ${a.is_available?'available':'unavailable'}`} key={a.id}><strong>{dayNames[a.weekday]}</strong><span>{a.start_time} – {a.end_time}</span><span>{a.is_available?'Available':'Unavailable'}</span><button onClick={()=>del(`/api/availability?id=${a.id}`)}>×</button></div>)}</div></article>)}</div></section>:<section className="leave-card"><div className="leave-list">{data.leaveRequests.length===0?<div className="empty-state">No leave requests.</div>:data.leaveRequests.map(r=><article className="leave-row" key={r.id}><div className="leave-person"><div className="avatar small">{initials(r.worker_name)}</div><div><strong>{r.worker_name}</strong><span>{r.leave_type}</span></div></div><div><strong>{fd(r.starts_on)} – {fd(r.ends_on)}</strong><span>{r.reason||'No reason'}</span></div><span className={`status ${r.status}`}>{r.status}</span><div className="leave-actions">{r.status==='pending'&&<><button className="approve-btn" onClick={()=>review(r.id,'approved')}>Approve</button><button className="reject-btn" onClick={()=>review(r.id,'rejected')}>Reject</button></>}</div></article>)}</div></section>}</section>
  {workerModal&&<div className="modal-backdrop" onMouseDown={()=>setWorkerModal(false)}><form className="modal" onSubmit={e=>{e.preventDefault();post('/api/workers',workerForm,()=>setWorkerModal(false))}} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><h2>Add worker</h2><button type="button" className="icon-btn" onClick={()=>setWorkerModal(false)}>×</button></div><label>Full name<input required value={workerForm.full_name} onChange={e=>setWorkerForm({...workerForm,full_name:e.target.value})}/></label><label>Role<input value={workerForm.role_title} onChange={e=>setWorkerForm({...workerForm,role_title:e.target.value})}/></label><label>Email<input value={workerForm.email} onChange={e=>setWorkerForm({...workerForm,email:e.target.value})}/></label><label>Weekly target<input type="number" value={workerForm.weekly_target_hours} onChange={e=>setWorkerForm({...workerForm,weekly_target_hours:e.target.value})}/></label><div className="modal-actions"><button className="primary" disabled={saving}>Save</button></div></form></div>}
  {shiftModal&&<div className="modal-backdrop" onMouseDown={()=>setShiftModal(false)}><form className="modal" onSubmit={e=>{e.preventDefault();post('/api/shifts',shiftForm,()=>setShiftModal(false))}} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><h2>Create shift</h2><button type="button" className="icon-btn" onClick={()=>setShiftModal(false)}>×</button></div><label>Worker<select value={shiftForm.worker_id} onChange={e=>setShiftForm({...shiftForm,worker_id:e.target.value})}>{data.workers.map(w=><option key={w.id} value={w.id}>{w.full_name}</option>)}</select></label><label>Title<input value={shiftForm.title} onChange={e=>setShiftForm({...shiftForm,title:e.target.value})}/></label><div className="form-grid"><label>Date<input type="date" value={shiftForm.date} onChange={e=>setShiftForm({...shiftForm,date:e.target.value})}/></label><label>Start<input type="time" value={shiftForm.start} onChange={e=>setShiftForm({...shiftForm,start:e.target.value})}/></label><label>End<input type="time" value={shiftForm.end} onChange={e=>setShiftForm({...shiftForm,end:e.target.value})}/></label></div><div className="modal-actions"><button className="primary" disabled={saving}>Create</button></div></form></div>}
  {avModal&&<div className="modal-backdrop" onMouseDown={()=>setAvModal(false)}><form className="modal" onSubmit={e=>{e.preventDefault();post('/api/availability',avForm,()=>{setAvModal(false);setPanel('availability')})}} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><h2>Add availability</h2><button type="button" className="icon-btn" onClick={()=>setAvModal(false)}>×</button></div><label>Worker<select value={avForm.worker_id} onChange={e=>setAvForm({...avForm,worker_id:e.target.value})}>{data.workers.map(w=><option key={w.id} value={w.id}>{w.full_name}</option>)}</select></label><label>Day<select value={avForm.weekday} onChange={e=>setAvForm({...avForm,weekday:e.target.value})}>{dayNames.map((d,i)=><option key={d} value={i}>{d}</option>)}</select></label><label>Rule<select value={avForm.is_available?'available':'unavailable'} onChange={e=>setAvForm({...avForm,is_available:e.target.value==='available'})}><option value="available">Available</option><option value="unavailable">Unavailable</option></select></label><div className="form-grid"><label>Start<input type="time" value={avForm.start_time} onChange={e=>setAvForm({...avForm,start_time:e.target.value})}/></label><label>End<input type="time" value={avForm.end_time} onChange={e=>setAvForm({...avForm,end_time:e.target.value})}/></label></div><label>Note<input value={avForm.note} onChange={e=>setAvForm({...avForm,note:e.target.value})}/></label><div className="modal-actions"><button className="primary" disabled={saving}>Save</button></div></form></div>}
  {leaveModal&&<div className="modal-backdrop" onMouseDown={()=>setLeaveModal(false)}><form className="modal" onSubmit={e=>{e.preventDefault();post('/api/leave',leaveForm,()=>{setLeaveModal(false);setPanel('leave')})}} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><h2>Request leave</h2><button type="button" className="icon-btn" onClick={()=>setLeaveModal(false)}>×</button></div><label>Worker<select value={leaveForm.worker_id} onChange={e=>setLeaveForm({...leaveForm,worker_id:e.target.value})}>{data.workers.map(w=><option key={w.id} value={w.id}>{w.full_name}</option>)}</select></label><label>Type<select value={leaveForm.leave_type} onChange={e=>setLeaveForm({...leaveForm,leave_type:e.target.value})}><option value="annual">Annual</option><option value="sick">Sick</option><option value="personal">Personal</option><option value="unpaid">Unpaid</option></select></label><div className="form-grid"><label>From<input type="date" value={leaveForm.starts_on} onChange={e=>setLeaveForm({...leaveForm,starts_on:e.target.value})}/></label><label>To<input type="date" value={leaveForm.ends_on} onChange={e=>setLeaveForm({...leaveForm,ends_on:e.target.value})}/></label></div><label>Reason<textarea value={leaveForm.reason} onChange={e=>setLeaveForm({...leaveForm,reason:e.target.value})}/></label><div className="modal-actions"><button className="primary" disabled={saving}>Submit</button></div></form></div>}
 </main>
}
