'use client';

import { useEffect, useMemo, useState } from 'react';

type Worker={id:number;full_name:string;role_title:string|null;email:string|null;weekly_target_hours:number};
type Shift={id:number;worker_id:number;title:string;starts_at:string;ends_at:string;status:string;notes:string|null};
type LeaveRequest={id:number;worker_id:number;worker_name:string;leave_type:string;starts_on:string;ends_on:string;reason:string|null;status:'pending'|'approved'|'rejected'|'cancelled';manager_note:string|null;created_at:string;reviewed_at:string|null};
type Dashboard={workers:Worker[];shifts:Shift[];leaveRequests:LeaveRequest[]};
type Panel='schedule'|'workers'|'leave';

function mondayOf(date:Date){const d=new Date(date);const day=d.getDay();d.setDate(d.getDate()+(day===0?-6:1-day));d.setHours(0,0,0,0);return d}
function dateKey(date:Date){const y=date.getFullYear();const m=String(date.getMonth()+1).padStart(2,'0');const d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`}
function fmtTime(value:string){return new Date(value).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}
function fmtDate(value:string){return new Date(`${value.slice(0,10)}T00:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}

export default function Home(){
  const [data,setData]=useState<Dashboard>({workers:[],shifts:[],leaveRequests:[]});
  const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [saving,setSaving]=useState(false);
  const [weekStart,setWeekStart]=useState(()=>mondayOf(new Date()));const [panel,setPanel]=useState<Panel>('schedule');
  const [shiftModal,setShiftModal]=useState(false);const [workerModal,setWorkerModal]=useState(false);const [leaveModal,setLeaveModal]=useState(false);
  const [shiftForm,setShiftForm]=useState({worker_id:'',title:'Shift',date:dateKey(new Date()),start:'09:00',end:'17:00',notes:''});
  const [workerForm,setWorkerForm]=useState({full_name:'',role_title:'',email:'',weekly_target_hours:'40'});
  const [leaveForm,setLeaveForm]=useState({worker_id:'',leave_type:'annual',starts_on:dateKey(new Date()),ends_on:dateKey(new Date()),reason:''});

  async function load(){setLoading(true);setError('');try{const res=await fetch('/api/dashboard',{cache:'no-store'});if(!res.ok)throw new Error(await res.text());const body=await res.json();setData({workers:body.workers||[],shifts:body.shifts||[],leaveRequests:body.leaveRequests||[]})}catch(e){setError(e instanceof Error?e.message:'Failed to load')}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);

  const days=useMemo(()=>Array.from({length:7},(_,i)=>{const d=new Date(weekStart);d.setDate(d.getDate()+i);return d}),[weekStart]);
  const weeklyShifts=useMemo(()=>data.shifts.filter(s=>{const d=new Date(s.starts_at);return d>=weekStart&&d<new Date(weekStart.getTime()+7*86400000)}),[data.shifts,weekStart]);
  const scheduledHours=weeklyShifts.reduce((sum,s)=>sum+(new Date(s.ends_at).getTime()-new Date(s.starts_at).getTime())/3600000,0);
  const workersScheduled=new Set(weeklyShifts.map(s=>s.worker_id)).size;
  const pendingLeave=data.leaveRequests.filter(r=>r.status==='pending').length;

  function openShiftModal(){const first=data.workers[0];setError('');setShiftForm({worker_id:first?String(first.id):'',title:'Shift',date:dateKey(days[0]||new Date()),start:'09:00',end:'17:00',notes:''});setShiftModal(true)}
  function openLeaveModal(){const first=data.workers[0];const today=dateKey(new Date());setError('');setLeaveForm({worker_id:first?String(first.id):'',leave_type:'annual',starts_on:today,ends_on:today,reason:''});setLeaveModal(true)}

  async function addWorker(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{const res=await fetch('/api/workers',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(workerForm)});const body=await res.json();if(!res.ok)throw new Error(body.error||'Could not create worker');setWorkerModal(false);setWorkerForm({full_name:'',role_title:'',email:'',weekly_target_hours:'40'});await load()}catch(e){setError(e instanceof Error?e.message:'Could not create worker')}finally{setSaving(false)}}
  async function addShift(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{const res=await fetch('/api/shifts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(shiftForm)});const body=await res.json();if(!res.ok)throw new Error(body.error||'Could not create shift');setShiftModal(false);await load()}catch(e){setError(e instanceof Error?e.message:'Could not create shift')}finally{setSaving(false)}}
  async function addLeave(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{const res=await fetch('/api/leave',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(leaveForm)});const body=await res.json();if(!res.ok)throw new Error(body.error||'Could not create leave request');setLeaveModal(false);setPanel('leave');await load()}catch(e){setError(e instanceof Error?e.message:'Could not create leave request')}finally{setSaving(false)}}
  async function reviewLeave(id:number,status:'approved'|'rejected'){setSaving(true);setError('');try{const res=await fetch('/api/leave',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,status})});const body=await res.json();if(!res.ok)throw new Error(body.error||'Could not update leave request');await load()}catch(e){setError(e instanceof Error?e.message:'Could not update leave request')}finally{setSaving(false)}}
  async function removeShift(id:number){if(!confirm('Delete this shift?'))return;const res=await fetch(`/api/shifts?id=${id}`,{method:'DELETE'});if(!res.ok){const body=await res.json();setError(body.error||'Could not delete shift');return}await load()}

  const moveWeek=(n:number)=>{const d=new Date(weekStart);d.setDate(d.getDate()+n*7);setWeekStart(d)};
  const initials=(name:string)=>name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();
  const pageTitle=panel==='schedule'?'Schedule':panel==='workers'?'Workers':'Leave requests';
  const pageSubtitle=panel==='schedule'?'Plan shifts, balance hours, and prevent conflicts.':panel==='workers'?'Manage the people available for scheduling.':'Review time-off requests and protect approved leave from scheduling.';

  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark">W</div><div><strong>Workly</strong><span>Scheduler</span></div></div><nav>
      <button className={panel==='schedule'?'active':''} onClick={()=>setPanel('schedule')}>Schedule</button>
      <button className={panel==='workers'?'active':''} onClick={()=>setPanel('workers')}>Workers</button>
      <button disabled>Availability</button>
      <button className={panel==='leave'?'active':''} onClick={()=>setPanel('leave')}>Leave requests {pendingLeave>0&&<span className="nav-count">{pendingLeave}</span>}</button>
      <button disabled>Reports</button>
    </nav><div className="profile"><div className="avatar">AD</div><div><strong>Admin</strong><span>Administrator</span></div></div></aside>

    <section className="content"><header className="topbar"><div><p className="eyebrow">WORKFORCE MANAGEMENT</p><h1>{pageTitle}</h1><p className="subtle">{pageSubtitle}</p></div><div className="top-actions">
      {panel==='workers'&&<button className="primary" onClick={()=>setWorkerModal(true)}>+ Worker</button>}
      {panel==='schedule'&&<><button className="secondary" onClick={()=>setWorkerModal(true)}>+ Worker</button><button className="primary" onClick={openShiftModal} disabled={!data.workers.length}>+ Add shift</button></>}
      {panel==='leave'&&<button className="primary" onClick={openLeaveModal} disabled={!data.workers.length}>+ Request leave</button>}
    </div></header>
    {error&&<div className="error-banner">{error}</div>}
    {loading?<div className="loading">Loading scheduler…</div>:panel==='schedule'?<>
      <section className="stats"><article><span>Scheduled hours</span><strong>{scheduledHours.toFixed(1)}h</strong><small>This week</small></article><article><span>Workers scheduled</span><strong>{workersScheduled}</strong><small>{data.workers.length} total workers</small></article><article><span>Shifts</span><strong>{weeklyShifts.length}</strong><small>Current week</small></article><article><span>Pending leave</span><strong>{pendingLeave}</strong><small>Needs review</small></article></section>
      <section className="calendar-card"><div className="calendar-toolbar"><div className="toolbar-left"><button onClick={()=>moveWeek(-1)}>‹</button><button onClick={()=>setWeekStart(mondayOf(new Date()))}>Today</button><button onClick={()=>moveWeek(1)}>›</button><strong>{days[0].toLocaleDateString(undefined,{month:'short',day:'numeric'})} – {days[6].toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</strong></div></div>
      <div className="schedule-grid"><div className="corner">Worker</div>{days.map(d=><div className="day-head" key={dateKey(d)}>{d.toLocaleDateString(undefined,{weekday:'short',day:'numeric'})}</div>)}{data.workers.map(w=><div className="row-fragment" key={w.id}><div className="worker-cell"><div className="avatar small">{initials(w.full_name)}</div><div><strong>{w.full_name}</strong><span>{w.role_title||'Worker'}</span></div></div>{days.map(d=>{const key=dateKey(d);const dayShifts=weeklyShifts.filter(s=>s.worker_id===w.id&&dateKey(new Date(s.starts_at))===key);const onLeave=data.leaveRequests.some(r=>r.worker_id===w.id&&r.status==='approved'&&r.starts_on.slice(0,10)<=key&&r.ends_on.slice(0,10)>=key);return <div className={`shift-cell ${onLeave?'leave-day':''}`} key={key}>{onLeave&&<div className="leave-chip">On leave</div>}{dayShifts.map(s=><button className="shift" key={s.id} onClick={()=>removeShift(s.id)} title="Click to delete"><strong>{s.title}</strong><span>{fmtTime(s.starts_at)} – {fmtTime(s.ends_at)}</span></button>)}</div>})}</div>)}</div></section>
    </>:panel==='workers'?<section className="workers-card"><div className="workers-table"><div className="table-head"><span>Name</span><span>Role</span><span>Email</span><span>Target</span></div>{data.workers.map(w=><div className="table-row" key={w.id}><span><div className="avatar small">{initials(w.full_name)}</div><strong>{w.full_name}</strong></span><span>{w.role_title||'—'}</span><span>{w.email||'—'}</span><span>{w.weekly_target_hours}h/week</span></div>)}</div></section>:<section className="leave-card">
      <div className="leave-summary"><div><strong>{pendingLeave}</strong><span>Pending</span></div><div><strong>{data.leaveRequests.filter(r=>r.status==='approved').length}</strong><span>Approved</span></div><div><strong>{data.leaveRequests.filter(r=>r.status==='rejected').length}</strong><span>Rejected</span></div></div>
      <div className="leave-list">{data.leaveRequests.length===0?<div className="empty-state">No leave requests yet.</div>:data.leaveRequests.map(r=><article className="leave-row" key={r.id}><div className="leave-person"><div className="avatar small">{initials(r.worker_name)}</div><div><strong>{r.worker_name}</strong><span>{r.leave_type.replace('_',' ')}</span></div></div><div><strong>{fmtDate(r.starts_on)}{r.starts_on.slice(0,10)!==r.ends_on.slice(0,10)?` – ${fmtDate(r.ends_on)}`:''}</strong><span>{r.reason||'No reason provided'}</span></div><span className={`status ${r.status}`}>{r.status}</span><div className="leave-actions">{r.status==='pending'?<><button className="approve-btn" disabled={saving} onClick={()=>reviewLeave(r.id,'approved')}>Approve</button><button className="reject-btn" disabled={saving} onClick={()=>reviewLeave(r.id,'rejected')}>Reject</button></>:<span className="reviewed">Reviewed</span>}</div></article>)}</div>
    </section>}
    </section>

    {workerModal&&<div className="modal-backdrop" onMouseDown={()=>setWorkerModal(false)}><form className="modal" onSubmit={addWorker} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">NEW WORKER</p><h2>Add worker</h2></div><button type="button" className="icon-btn" onClick={()=>setWorkerModal(false)}>×</button></div><label>Full name<input required value={workerForm.full_name} onChange={e=>setWorkerForm({...workerForm,full_name:e.target.value})}/></label><label>Role<input value={workerForm.role_title} onChange={e=>setWorkerForm({...workerForm,role_title:e.target.value})}/></label><label>Email<input type="email" value={workerForm.email} onChange={e=>setWorkerForm({...workerForm,email:e.target.value})}/></label><label>Weekly target hours<input type="number" min="1" max="168" value={workerForm.weekly_target_hours} onChange={e=>setWorkerForm({...workerForm,weekly_target_hours:e.target.value})}/></label><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setWorkerModal(false)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Add worker'}</button></div></form></div>}

    {shiftModal&&<div className="modal-backdrop" onMouseDown={()=>setShiftModal(false)}><form className="modal" onSubmit={addShift} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">NEW SHIFT</p><h2>Create shift</h2></div><button type="button" className="icon-btn" onClick={()=>setShiftModal(false)}>×</button></div><label>Worker<select required value={shiftForm.worker_id} onChange={e=>setShiftForm({...shiftForm,worker_id:e.target.value})}>{data.workers.map(w=><option value={w.id} key={w.id}>{w.full_name}</option>)}</select></label><label>Shift title<input required value={shiftForm.title} onChange={e=>setShiftForm({...shiftForm,title:e.target.value})}/></label><div className="form-grid"><label>Date<input type="date" required value={shiftForm.date} onChange={e=>setShiftForm({...shiftForm,date:e.target.value})}/></label><label>Start<input type="time" required value={shiftForm.start} onChange={e=>setShiftForm({...shiftForm,start:e.target.value})}/></label><label>End<input type="time" required value={shiftForm.end} onChange={e=>setShiftForm({...shiftForm,end:e.target.value})}/></label></div><label>Notes<textarea rows={3} value={shiftForm.notes} onChange={e=>setShiftForm({...shiftForm,notes:e.target.value})}/></label><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setShiftModal(false)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Create shift'}</button></div></form></div>}

    {leaveModal&&<div className="modal-backdrop" onMouseDown={()=>setLeaveModal(false)}><form className="modal" onSubmit={addLeave} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">TIME OFF</p><h2>Request leave</h2></div><button type="button" className="icon-btn" onClick={()=>setLeaveModal(false)}>×</button></div><label>Worker<select required value={leaveForm.worker_id} onChange={e=>setLeaveForm({...leaveForm,worker_id:e.target.value})}>{data.workers.map(w=><option value={w.id} key={w.id}>{w.full_name}</option>)}</select></label><label>Leave type<select value={leaveForm.leave_type} onChange={e=>setLeaveForm({...leaveForm,leave_type:e.target.value})}><option value="annual">Annual leave</option><option value="sick">Sick leave</option><option value="personal">Personal leave</option><option value="unpaid">Unpaid leave</option></select></label><div className="leave-date-grid"><label>From<input type="date" required value={leaveForm.starts_on} onChange={e=>setLeaveForm({...leaveForm,starts_on:e.target.value,ends_on:e.target.value>leaveForm.ends_on?e.target.value:leaveForm.ends_on})}/></label><label>To<input type="date" required min={leaveForm.starts_on} value={leaveForm.ends_on} onChange={e=>setLeaveForm({...leaveForm,ends_on:e.target.value})}/></label></div><label>Reason<textarea rows={3} value={leaveForm.reason} onChange={e=>setLeaveForm({...leaveForm,reason:e.target.value})} placeholder="Optional note"/></label><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setLeaveModal(false)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Submit request'}</button></div></form></div>}
  </main>
}
